site_name: BMEVIAUAC09 Software development laboratory 1
site_author: Dudás Ákos
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauac01/laboratories-en
repo_url: https://github.com/bmeviauac01/laboratories-en

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
  logo: images/logo-bme-aut.png
  favicon: images/favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - "Software development laboratory 1":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - FAQ.md
      - VisualStudio.md
      - bme-cloud-vm.md
      - GitHub-credentials.md
  - "Reporting Services":
      - Lab-ReportingServices/index.md
      - Lab-ReportingServices/Exercise-1.md
      - Lab-ReportingServices/Exercise-2.md
      - Lab-ReportingServices/Exercise-3.md
      - Lab-ReportingServices/Exercise-4.md
  - "Query optimization":
      - Lab-QueryOptimization/index.md
      - Lab-QueryOptimization/Exercise-1.md
      - Lab-QueryOptimization/Exercise-2.md
      - Lab-QueryOptimization/Exercise-3.md
  - "MSSQL":
      - Lab-MSSQL/index.md
      - Lab-MSSQL/Exercise-1.md
      - Lab-MSSQL/Exercise-2.md
      - Lab-MSSQL/Exercise-3.md
      - Lab-MSSQL/Exercise-4.md
  - "MongoDB":
      - Lab-MongoDB/index.md
      - Lab-MongoDB/Exercise-1.md
      - Lab-MongoDB/Exercise-2.md
      - Lab-MongoDB/Exercise-3.md
      - Lab-MongoDB/Exercise-4.md
      - Lab-MongoDB/Exercise-5.md
  - "Entity Framework & REST":
      - Lab-EFREST/index.md
      - Lab-EFREST/Exercise-1.md
      - Lab-EFREST/Exercise-2.md
      - Lab-EFREST/Exercise-3.md
      - Lab-EFREST/Exercise-4.md
