site_name: BMEVIAUAC09 Szoftverfejlesztés laboratórium 1
site_author: Dudás Ákos
copyright: Copyright &copy; BME AUT
repo_name: bmeviauac01/laborok
repo_url: https://github.com/bmeviauac01/laborok

theme:
  name: material
  custom_dir: theme-overrides
  language: hu
  palette:
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  logo: images/logo-bme-aut.png
  favicon: images/favicon.ico

extra_css:
  - extra-material-theme.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - "Szoftverfejlesztés laboratórium 1":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - FAQ.md
      - VisualStudio.md
      - GitHub-credentials.md
  - "Reporting Services":
      - Lab-ReportingServices/index.md
      - Lab-ReportingServices/Feladat-1.md
      - Lab-ReportingServices/Feladat-2.md
      - Lab-ReportingServices/Feladat-3.md
      - Lab-ReportingServices/Feladat-4.md
  - "Lekérdezés optimalizálás":
      - Lab-QueryOptimization/index.md
      - Lab-QueryOptimization/Feladat-1.md
      - Lab-QueryOptimization/Feladat-2.md
      - Lab-QueryOptimization/Feladat-3.md
  - "MSSQL":
      - Lab-MSSQL/index.md
      - Lab-MSSQL/Feladat-1.md
      - Lab-MSSQL/Feladat-2.md
      - Lab-MSSQL/Feladat-3.md
      - Lab-MSSQL/Feladat-4.md
  - "MongoDB":
      - Lab-MongoDB/index.md
      - Lab-MongoDB/Feladat-1.md
      - Lab-MongoDB/Feladat-2.md
      - Lab-MongoDB/Feladat-3.md
      - Lab-MongoDB/Feladat-4.md
      - Lab-MongoDB/Feladat-5.md
  - "Entity Framework & REST":
      - Lab-EFREST/index.md
      - Lab-EFREST/Feladat-1.md
      - Lab-EFREST/Feladat-2.md
      - Lab-EFREST/Feladat-3.md
      - Lab-EFREST/Feladat-4.md
